import type { DayItinerary } from '@/types/voyage';

// ─── Static example itinerary used for the welcome-offer preview and the
// paywall "see an example" link. Not fetched from the AI — a hand-written
// sample in the same shape ai.generateItinerary returns, so it can be
// rendered with the same read-only preview UI everywhere it's shown.

export interface ExampleItinerary {
  id: string;
  destinationName: string;
  country: string;
  totalDays: number;
  days: DayItinerary[];
}

export const EXAMPLE_ITINERARY_PARIS: ExampleItinerary = {
  id: 'example-paris-3d',
  destinationName: 'Paris',
  country: 'França',
  totalDays: 3,
  days: [
    {
      date: '2026-05-12',
      destination: 'Paris',
      dayNumber: 1,
      title: 'Chegada em Paris — Torre Eiffel e Champs-Élysées',
      tip: 'Compre o ingresso da Torre Eiffel com antecedência para pular a fila.',
      estimatedCost: 95,
      estimatedCostCurrency: 'EUR',
      stops: [
        {
          id: 'ex-paris-d1-s1',
          time: '09:00',
          placeName: 'Café de Flore',
          placeCategory: 'cafe',
          description: 'Café histórico de Saint-Germain, ótimo para um croissant e um café antes de começar o dia.',
          address: '172 Boulevard Saint-Germain, 75006 Paris',
          lat: 48.8539,
          lng: 2.3325,
          hours: '07:30–01:30',
          travelTimeToNext: '25 min de metrô',
          travelModeToNext: 'public',
        },
        {
          id: 'ex-paris-d1-s2',
          time: '10:30',
          placeName: 'Torre Eiffel',
          placeCategory: 'attraction',
          description: 'Suba até o segundo andar para uma vista panorâmica de Paris — o símbolo máximo da cidade.',
          address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris',
          lat: 48.8584,
          lng: 2.2945,
          hours: '09:00–23:45',
          travelTimeToNext: '15 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d1-s3',
          time: '13:00',
          placeName: 'Le Comptoir du 7ème',
          placeCategory: 'restaurant',
          description: 'Bistrô parisiense clássico perto do Campo de Marte, bom custo-benefício para o almoço.',
          address: '32 Avenue de la Bourdonnais, 75007 Paris',
          lat: 48.8578,
          lng: 2.3005,
          hours: '12:00–15:00, 19:00–23:00',
          travelTimeToNext: '20 min de metrô',
          travelModeToNext: 'public',
        },
        {
          id: 'ex-paris-d1-s4',
          time: '15:00',
          placeName: 'Arco do Triunfo',
          placeCategory: 'attraction',
          description: 'Suba ao topo para outra vista incrível, olhando para as 12 avenidas que se encontram na praça.',
          address: 'Place Charles de Gaulle, 75008 Paris',
          lat: 48.8738,
          lng: 2.2950,
          hours: '10:00–23:00',
          travelTimeToNext: '10 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d1-s5',
          time: '16:00',
          placeName: 'Champs-Élysées',
          placeCategory: 'attraction',
          description: 'Passeio pela avenida mais famosa de Paris, com lojas, cafés e vitrines icônicas.',
          address: 'Avenue des Champs-Élysées, 75008 Paris',
          lat: 48.8698,
          lng: 2.3079,
          hours: '24h',
          travelTimeToNext: '30 min de metrô',
          travelModeToNext: 'public',
        },
        {
          id: 'ex-paris-d1-s6',
          time: '20:00',
          placeName: 'Le Relais de l\'Entrecôte',
          placeCategory: 'restaurant',
          description: 'Restaurante tradicional famoso pelo steak-frites com molho secreto — um clássico parisiense.',
          address: '15 Rue Marbeuf, 75008 Paris',
          lat: 48.8687,
          lng: 2.3010,
          hours: '19:00–23:00',
        },
      ],
    },
    {
      date: '2026-05-13',
      destination: 'Paris',
      dayNumber: 2,
      title: 'Arte e história — Louvre e Notre-Dame',
      tip: 'O Louvre é gigantesco: escolha 2 ou 3 alas para não se cansar demais.',
      estimatedCost: 80,
      estimatedCostCurrency: 'EUR',
      stops: [
        {
          id: 'ex-paris-d2-s1',
          time: '08:30',
          placeName: 'Boulangerie Julien',
          placeCategory: 'cafe',
          description: 'Padaria premiada para um café da manhã simples com croissants recém-saídos do forno.',
          address: '75 Rue Saint-Honoré, 75001 Paris',
          lat: 48.8610,
          lng: 2.3450,
          hours: '07:00–20:00',
          travelTimeToNext: '10 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d2-s2',
          time: '09:30',
          placeName: 'Museu do Louvre',
          placeCategory: 'museum',
          description: 'Um dos maiores museus do mundo — Mona Lisa, Vênus de Milo e milhares de outras obras-primas.',
          address: 'Rue de Rivoli, 75001 Paris',
          lat: 48.8606,
          lng: 2.3376,
          hours: '09:00–18:00',
          travelTimeToNext: '15 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d2-s3',
          time: '13:00',
          placeName: 'Le Fumoir',
          placeCategory: 'restaurant',
          description: 'Restaurante elegante a poucos passos do Louvre, ótimo para um almoço mais tranquilo.',
          address: '6 Rue de l\'Amiral de Coligny, 75001 Paris',
          lat: 48.8604,
          lng: 2.3406,
          hours: '11:00–02:00',
          travelTimeToNext: '20 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d2-s4',
          time: '14:30',
          placeName: 'Notre-Dame de Paris',
          placeCategory: 'attraction',
          description: 'A catedral gótica mais famosa do mundo, reaberta após a restauração — vale ver o exterior e a Île de la Cité.',
          address: '6 Parvis Notre-Dame, 75004 Paris',
          lat: 48.8530,
          lng: 2.3499,
          hours: '08:00–19:00',
          travelTimeToNext: '10 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d2-s5',
          time: '16:00',
          placeName: 'Sainte-Chapelle',
          placeCategory: 'hidden_gem',
          description: 'Capela gótica com um dos conjuntos de vitrais medievais mais impressionantes da Europa — menos concorrida que Notre-Dame.',
          address: '8 Boulevard du Palais, 75001 Paris',
          lat: 48.8554,
          lng: 2.3450,
          hours: '09:00–17:00',
          travelTimeToNext: '25 min de metrô',
          travelModeToNext: 'public',
        },
        {
          id: 'ex-paris-d2-s6',
          time: '19:30',
          placeName: 'Chez Janou',
          placeCategory: 'restaurant',
          description: 'Bistrô provençal aconchegante no Marais, famoso pela mousse de chocolate gigante de sobremesa.',
          address: '2 Rue Roger Verlomme, 75003 Paris',
          lat: 48.8578,
          lng: 2.3654,
          hours: '12:00–15:00, 19:00–23:30',
        },
      ],
    },
    {
      date: '2026-05-14',
      destination: 'Paris',
      dayNumber: 3,
      title: 'Montmartre e despedida de Paris',
      tip: 'Chegue cedo em Montmartre para fotografar as ruas vazias antes dos grupos turísticos.',
      estimatedCost: 60,
      estimatedCostCurrency: 'EUR',
      stops: [
        {
          id: 'ex-paris-d3-s1',
          time: '09:00',
          placeName: 'Coquelicot Montmartre',
          placeCategory: 'cafe',
          description: 'Padaria charmosa aos pés da colina de Montmartre, ideal para o café da manhã.',
          address: '24 Rue des Abbesses, 75018 Paris',
          lat: 48.8847,
          lng: 2.3389,
          hours: '08:00–19:00',
          travelTimeToNext: '15 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d3-s2',
          time: '10:00',
          placeName: 'Sacré-Cœur',
          placeCategory: 'attraction',
          description: 'Basílica no topo de Montmartre com uma das vistas mais bonitas de Paris.',
          address: '35 Rue du Chevalier de la Barre, 75018 Paris',
          lat: 48.8867,
          lng: 2.3431,
          hours: '06:00–22:30',
          travelTimeToNext: '5 min a pé',
          travelModeToNext: 'walking' as any,
        },
        {
          id: 'ex-paris-d3-s3',
          time: '11:30',
          placeName: 'Place du Tertre',
          placeCategory: 'hidden_gem',
          description: 'Praça pitoresca cheia de pintores de rua, no coração do vilarejo boêmio de Montmartre.',
          address: 'Place du Tertre, 75018 Paris',
          lat: 48.8867,
          lng: 2.3407,
          hours: '24h',
          travelTimeToNext: '20 min de metrô',
          travelModeToNext: 'public',
        },
        {
          id: 'ex-paris-d3-s4',
          time: '13:00',
          placeName: 'Bistrot Paul Bert',
          placeCategory: 'restaurant',
          description: 'Bistrô parisiense autêntico, perfeito para uma última refeição memorável antes da partida.',
          address: '18 Rue Paul Bert, 75011 Paris',
          lat: 48.8534,
          lng: 2.3823,
          hours: '12:00–14:30, 19:30–23:00',
        },
      ],
    },
  ],
};

export const EXAMPLE_ITINERARIES: ExampleItinerary[] = [EXAMPLE_ITINERARY_PARIS];
